// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using FabricApp.Data;
using FabricApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace FabricApp.Data.Configurations
{
    public partial class ClothMaterialConfiguration : IEntityTypeConfiguration<ClothMaterial>
    {
        public void Configure(EntityTypeBuilder<ClothMaterial> entity)
        {
            entity.HasNoKey();

            entity.ToTable("cloth_materials");

            entity.HasIndex(e => e.ClothId, "IX_Cloth_Cloths");

            entity.HasIndex(e => e.ClothId, "IX_Cloth_Material");

            entity.Property(e => e.ClothId).HasColumnName("cloth_id");

            entity.Property(e => e.MaterialId).HasColumnName("material_id");

            entity.Property(e => e.Percentage).HasColumnName("percentage");

            entity.HasOne(d => d.Cloth)
                .WithMany()
                .HasForeignKey(d => d.ClothId)
                .HasConstraintName("FK_cloth_materials_cloths");

            entity.HasOne(d => d.Material)
                .WithMany()
                .HasForeignKey(d => d.MaterialId)
                .HasConstraintName("FK_cloth_materials_materials");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ClothMaterial> entity);
    }
}
