// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using FabricApp.Data;
using FabricApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace FabricApp.Data.Configurations
{
    public partial class FurnitureConfiguration : IEntityTypeConfiguration<Furniture>
    {
        public void Configure(EntityTypeBuilder<Furniture> entity)
        {
            entity.ToTable("furniture");

            entity.HasIndex(e => e.Id, "IX_furniture_and_types");

            entity.Property(e => e.Id).HasColumnName("id");

            entity.Property(e => e.Image).HasColumnName("image");

            entity.Property(e => e.Length).HasColumnName("length");

            entity.Property(e => e.Name)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("name");

            entity.Property(e => e.Price).HasColumnName("price");

            entity.Property(e => e.TypeId).HasColumnName("type_id");

            entity.Property(e => e.Weight).HasColumnName("weight");

            entity.Property(e => e.Width).HasColumnName("width");

            entity.HasOne(d => d.Type)
                .WithMany(p => p.Furnitures)
                .HasForeignKey(d => d.TypeId)
                .HasConstraintName("FK_furniture_furniture_types");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Furniture> entity);
    }
}
