// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using FabricApp.Data;
using FabricApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace FabricApp.Data.Configurations
{
    public partial class OrderConfiguration : IEntityTypeConfiguration<Order>
    {
        public void Configure(EntityTypeBuilder<Order> entity)
        {
            entity.ToTable("orders");

            entity.HasIndex(e => e.Id, "IX_customer_and_users");

            entity.HasIndex(e => e.Id, "IX_manager_and_users");

            entity.Property(e => e.Id).HasColumnName("id");

            entity.Property(e => e.Customer).HasColumnName("customer");

            entity.Property(e => e.Date)
                .HasColumnType("date")
                .HasColumnName("date");

            entity.Property(e => e.Manager).HasColumnName("manager");

            entity.Property(e => e.Price).HasColumnName("price");

            entity.Property(e => e.Stage)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("stage");

            entity.HasOne(d => d.CustomerNavigation)
                .WithMany(p => p.OrderCustomerNavigations)
                .HasForeignKey(d => d.Customer)
                .HasConstraintName("FK_orders_users");

            entity.HasOne(d => d.ManagerNavigation)
                .WithMany(p => p.OrderManagerNavigations)
                .HasForeignKey(d => d.Manager)
                .HasConstraintName("FK_orders_users1");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Order> entity);
    }
}
