// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FabricApp.Models
{
    public partial class ClothMaterial
    {
        public long? ClothId { get; set; }
        public long? MaterialId { get; set; }
        public byte? Percentage { get; set; }

        public virtual Cloth Cloth { get; set; }
        public virtual Material Material { get; set; }
    }
}