// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FabricApp.Models
{
    public partial class Cloth
    {
        public Cloth()
        {
            WarehouseCloths = new HashSet<WarehouseCloth>();
        }

        public long Id { get; set; }
        public string Name { get; set; }
        public string Color { get; set; }
        public string Pattern { get; set; }
        public byte[] Image { get; set; }
        public double? Width { get; set; }
        public double? Length { get; set; }
        public int? Price { get; set; }

        public virtual ICollection<WarehouseCloth> WarehouseCloths { get; set; }
    }
}