// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FabricApp.Models
{
    public partial class Order
    {
        public long Id { get; set; }
        public DateTime? Date { get; set; }
        public string Stage { get; set; }
        public long? Customer { get; set; }
        public long? Manager { get; set; }
        public double? Price { get; set; }

        public virtual User CustomerNavigation { get; set; }
        public virtual User ManagerNavigation { get; set; }
    }
}