// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FabricApp.Models
{
    public partial class ProductCloth
    {
        public long? ProductId { get; set; }
        public long? ClothId { get; set; }

        public virtual Cloth Cloth { get; set; }
        public virtual Product Product { get; set; }
    }
}