// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FabricApp.Models
{
    public partial class ProductFurniture
    {
        public long? ProductId { get; set; }
        public long? FurnitureId { get; set; }

        public virtual Furniture Furniture { get; set; }
        public virtual Product Product { get; set; }
    }
}