// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FabricApp.Models
{
    public partial class Product
    {
        public long Id { get; set; }
        public double? Width { get; set; }
        public double? Length { get; set; }
        public double? Rotation { get; set; }
        public int? Amount { get; set; }
    }
}