// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using FabricApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace FabricApp.Models.Configurations
{
    public partial class ProductClothConfiguration : IEntityTypeConfiguration<ProductCloth>
    {
        public void Configure(EntityTypeBuilder<ProductCloth> entity)
        {
            entity.HasNoKey();

            entity.ToTable("product_cloths");

            entity.HasIndex(e => e.ProductId, "IX_product_cloths_and_cloths");

            entity.HasIndex(e => e.ProductId, "IX_product_cloths_and_products");

            entity.Property(e => e.ClothId).HasColumnName("cloth_id");

            entity.Property(e => e.ProductId).HasColumnName("product_id");

            entity.HasOne(d => d.Cloth)
                .WithMany()
                .HasForeignKey(d => d.ClothId)
                .HasConstraintName("FK_product_cloths_cloths");

            entity.HasOne(d => d.Product)
                .WithMany()
                .HasForeignKey(d => d.ProductId)
                .HasConstraintName("FK_product_cloths_products");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ProductCloth> entity);
    }
}
