// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using FabricApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace FabricApp.Models.Configurations
{
    public partial class WarehouseClothConfiguration : IEntityTypeConfiguration<WarehouseCloth>
    {
        public void Configure(EntityTypeBuilder<WarehouseCloth> entity)
        {
            entity.ToTable("warehouse_cloths");

            entity.HasIndex(e => e.Id, "IX_warehouse_cloths_and_cloth");

            entity.Property(e => e.Id).HasColumnName("id");

            entity.Property(e => e.ClothId).HasColumnName("cloth_id");

            entity.Property(e => e.Length).HasColumnName("length");

            entity.HasOne(d => d.Cloth)
                .WithMany(p => p.WarehouseCloths)
                .HasForeignKey(d => d.ClothId)
                .HasConstraintName("FK_warehouse_cloths_cloths");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<WarehouseCloth> entity);
    }
}
