// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using FabricApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace FabricApp.Models.Configurations
{
    public partial class WarehouseFurnitureConfiguration : IEntityTypeConfiguration<WarehouseFurniture>
    {
        public void Configure(EntityTypeBuilder<WarehouseFurniture> entity)
        {
            entity.ToTable("warehouse_furnitures");

            entity.HasIndex(e => e.Id, "IX_warehouse_furnitures_and_furniture");

            entity.Property(e => e.Id).HasColumnName("id");

            entity.Property(e => e.Amount).HasColumnName("amount");

            entity.Property(e => e.FurnitureId).HasColumnName("furniture_id");

            entity.HasOne(d => d.Furniture)
                .WithMany(p => p.WarehouseFurnitures)
                .HasForeignKey(d => d.FurnitureId)
                .HasConstraintName("FK_warehouse_furnitures_furniture");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<WarehouseFurniture> entity);
    }
}
